def get_player_data
  player_data = [
                    {
                    first_name: "Novak",
                    last_name: "DJOKOVIC",
                    birthdate: "",
                    age: "",
                    country: "SRB",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "1",
                    draw_line_number: "1",
                    photo: "",
                    notes: ""
                  },
                    {
                    first_name: "Andy",
                    last_name: "MURRAY",
                    birthdate: "",
                    age: "",
                    country: "GBR",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "2",
                    draw_line_number: "128",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Roger",
                    last_name: "FEDERER",
                    birthdate: "",
                    age: "",
                    country: "SUI",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "3",
                    draw_line_number: "33",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Stan",
                    last_name: "WAWRINKA",
                    birthdate: "",
                    age: "",
                    country: "SUI",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "4",
                    draw_line_number: "96",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Jack",
                    last_name: "SOCK",
                    birthdate: "",
                    age: "",
                    country: "USA",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "5",
                    draw_line_number: "14",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Tomas",
                    last_name: "BERDYCH",
                    birthdate: "",
                    age: "",
                    country: "CZE",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "6",
                    draw_line_number: "64",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Kei",
                    last_name: "NISHIKORI",
                    birthdate: "",
                    age: "",
                    country: "JPN",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "7",
                    draw_line_number: "32",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "David",
                    last_name: "FERRER",
                    birthdate: "",
                    age: "",
                    country: "ESP",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "8",
                    draw_line_number: "97",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Jo-Wilfried",
                    last_name: "TSONGA",
                    birthdate: "",
                    age: "",
                    country: "FRA",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "9",
                    draw_line_number: "17",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "John",
                    last_name: "ISNER",
                    birthdate: "",
                    age: "",
                    country: "USA",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "10",
                    draw_line_number: "112",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Kevin",
                    last_name: "ANDERSON",
                    birthdate: "",
                    age: "",
                    country: "RSA",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "11",
                    draw_line_number: "80",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Marin",
                    last_name: "CILIC",
                    birthdate: "",
                    age: "",
                    country: "CRO",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "12",
                    draw_line_number: "49",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Milos",
                    last_name: "RAONIC",
                    birthdate: "",
                    age: "",
                    country: "CAN",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "13",
                    draw_line_number: "81",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Gilles",
                    last_name: "SIMON",
                    birthdate: "",
                    age: "",
                    country: "FRA",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "14",
                    draw_line_number: "16",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "David",
                    last_name: "GOFFIN",
                    birthdate: "",
                    age: "",
                    country: "BEL",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "15",
                    draw_line_number: "48",
                    photo: "",
                    notes: ""
                  },
                  {

                    first_name: "Bernard",
                    last_name: "TOMIC",
                    birthdate: "",
                    age: "",
                    country: "AUS",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "16",
                    draw_line_number: "113",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Serena",
                    last_name: "WILLIAMS",
                    birthdate: "",
                    age: "",
                    country: "USA",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "1",
                    draw_line_number: "1",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Simona",
                    last_name: "HALEP",
                    birthdate: "",
                    age: "",
                    country: "ROU",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "2",
                    draw_line_number: "128",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "GarbiÃ±e",
                    last_name: "MUGURUZA",
                    birthdate: "",
                    age: "",
                    country: "ESP",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "3",
                    draw_line_number: "96",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Agnieszka",
                    last_name: "RADWANSKA",
                    birthdate: "",
                    age: "",
                    country: "POL",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "4",
                    draw_line_number: "33",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Maria",
                    last_name: "SHARAPOVA",
                    birthdate: "",
                    age: "",
                    country: "RUS",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "5",
                    draw_line_number: "32",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Petra",
                    last_name: "KVITOVA",
                    birthdate: "",
                    age: "",
                    country: "CZE",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "6",
                    draw_line_number: "64",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Angelique",
                    last_name: "KERBER",
                    birthdate: "",
                    age: "",
                    country: "GER",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "7",
                    draw_line_number: "65",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Venus",
                    last_name: "WILLIAMS",
                    birthdate: "",
                    age: "",
                    country: "USA",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "8",
                    draw_line_number: "97",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Karolina",
                    last_name: "PLISKOVA",
                    birthdate: "",
                    age: "",
                    country: "CZE",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "9",
                    draw_line_number: "112",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Carla",
                    last_name: "SUÃREZ NAVARRO",
                    birthdate: "",
                    age: "",
                    country: "ESP",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "10",
                    draw_line_number: "49",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Timea",
                    last_name: "BACSINSZKY",
                    birthdate: "",
                    age: "",
                    country: "SUI",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "11",
                    draw_line_number: "80",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Belinda",
                    last_name: "BENCIC",
                    birthdate: "",
                    age: "",
                    country: "SUI",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "12",
                    draw_line_number: "17",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Roberta",
                    last_name: "VINCI",
                    birthdate: "",
                    age: "",
                    country: "ITA",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "13",
                    draw_line_number: "48",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Victoria",
                    last_name: "AZARENKA",
                    birthdate: "",
                    age: "",
                    country: "BLR",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "14",
                    draw_line_number: "81",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Madison",
                    last_name: "KEYS",
                    birthdate: "",
                    age: "",
                    country: "USA",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "15",
                    draw_line_number: "113",
                    photo: "",
                    notes: ""
                  },
                  {
                    first_name: "Caroline",
                    last_name: "WOZNIACKI",
                    birthdate: "",
                    age: "",
                    country: "DEN",
                    ranking: "",
                    gender: "female",
                    tournament: "",
                    seed: "16",
                    draw_line_number: "16",
                    photo: "",
                    notes: ""
                  },


    ]
  return player_data
end



