def get_player_data
  player_data = [
                    {
                    first_name: "Novak",
                    last_name: "DJOKOVIC",
                    birthdate: "May 22, 1987",
                    age: "28",
                    country: "SRB",
                    ranking: "1",
                    gender: "male",
                    tournament: "",
                    seed: "1",
                    draw_line_number: "1",
                    photo: "http://www.atpworldtour.com/~/media/tennis/players/head-shot/vibrant/djokovic-headshot15.png",
                    notes: ""
                  },
                    {
                    first_name: "Andy",
                    last_name: "MURRAY",
                    birthdate: "May 15, 1987",
                    age: "28",
                    country: "GBR",
                    ranking: "2",
                    gender: "male",
                    tournament: "",
                    seed: "2",
                    draw_line_number: "128",
                    photo: "http://www.ausopen.com/images/players/atpmc10.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Roger",
                    last_name: "FEDERER",
                    birthdate: "August 8, 1981",
                    age: "34",
                    country: "SUI",
                    ranking: "3",
                    gender: "male",
                    tournament: "",
                    seed: "3",
                    draw_line_number: "33",
                    photo: "http://www.ausopen.com/images/players/atpf324.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Stan",
                    last_name: "WAWRINKA",
                    birthdate: "March 28, 1985",
                    age: "30",
                    country: "SUI",
                    ranking: "4",
                    gender: "male",
                    tournament: "",
                    seed: "4",
                    draw_line_number: "96",
                    photo: "http://www.ausopen.com/images/players/atpw367.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Rafael",
                    last_name: "NADAL",
                    birthdate: "June 3, 1986",
                    age: "29",
                    country: "USA",
                    ranking: "5",
                    gender: "male",
                    tournament: "",
                    seed: "5",
                    draw_line_number: "65",
                    photo: "http://www.ausopen.com/images/players/atpn409.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Tomas",
                    last_name: "BERDYCH",
                    birthdate: "September 17, 1985",
                    age: "30",
                    country: "CZE",
                    ranking: "6",
                    gender: "male",
                    tournament: "",
                    seed: "6",
                    draw_line_number: "64",
                    photo: "http://www.ausopen.com/images/players/atpba47.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Kei",
                    last_name: "NISHIKORI",
                    birthdate: "December 29, 1989",
                    age: "26",
                    country: "JPN",
                    ranking: "",
                    gender: "male",
                    tournament: "",
                    seed: "7",
                    draw_line_number: "32",
                    photo: "http://www.ausopen.com/images/players/atpn552.jpg",
                    notes: ""
                  },
                  {
                    first_name: "David",
                    last_name: "FERRER",
                    birthdate: "April 2, 1982",
                    age: "33",
                    country: "ESP",
                    ranking: "8",
                    gender: "male",
                    tournament: "",
                    seed: "8",
                    draw_line_number: "97",
                    photo: "http://www.ausopen.com/images/players/atpf401.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Jo-Wilfried",
                    last_name: "TSONGA",
                    birthdate: "April 17, 1985",
                    age: "30",
                    country: "FRA",
                    ranking: "10",
                    gender: "male",
                    tournament: "",
                    seed: "9",
                    draw_line_number: "17",
                    photo: "http://www.ausopen.com/images/players/atpt786.jpg",
                    notes: ""
                  },
                  {
                    first_name: "John",
                    last_name: "ISNER",
                    birthdate: "April 26, 1985",
                    age: "30",
                    country: "USA",
                    ranking: "11",
                    gender: "male",
                    tournament: "",
                    seed: "10",
                    draw_line_number: "112",
                    photo: "http://www.ausopen.com/images/players/atpi186.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Kevin",
                    last_name: "ANDERSON",
                    birthdate: "May, 18 1986",
                    age: "29",
                    country: "RSA",
                    ranking: "12",
                    gender: "male",
                    tournament: "",
                    seed: "11",
                    draw_line_number: "80",
                    photo: "http://www.ausopen.com/images/players/atpa678.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Marin",
                    last_name: "CILIC",
                    birthdate: "September 28, 1988",
                    age: "27",
                    country: "CRO",
                    ranking: "13",
                    gender: "male",
                    tournament: "",
                    seed: "12",
                    draw_line_number: "49",
                    photo: "http://www.ausopen.com/images/players/atpc977.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Milos",
                    last_name: "RAONIC",
                    birthdate: "December 27, 1990",
                    age: "25",
                    country: "CAN",
                    ranking: "14",
                    gender: "male",
                    tournament: "",
                    seed: "13",
                    draw_line_number: "81",
                    photo: "http://www.ausopen.com/images/players/atpr975.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Gilles",
                    last_name: "SIMON",
                    birthdate: "December 27, 1984",
                    age: "31",
                    country: "FRA",
                    ranking: "15",
                    gender: "male",
                    tournament: "",
                    seed: "14",
                    draw_line_number: "16",
                    photo: "http://www.ausopen.com/images/players/atpsd32.jpg",
                    notes: ""
                  },
                  {
                    first_name: "David",
                    last_name: "GOFFIN",
                    birthdate: "December 7, 1990",
                    age: "25",
                    country: "BEL",
                    ranking: "16",
                    gender: "male",
                    tournament: "",
                    seed: "15",
                    draw_line_number: "48",
                    photo: "http://www.ausopen.com/images/players/atpgb88.jpg",
                    notes: ""
                  },
                  {

                    first_name: "Bernard",
                    last_name: "TOMIC",
                    birthdate: "October 21, 1992",
                    age: "23",
                    country: "AUS",
                    ranking: "17",
                    gender: "male",
                    tournament: "",
                    seed: "16",
                    draw_line_number: "113",
                    photo: "http://www.ausopen.com/images/players/atpta46.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Serena",
                    last_name: "WILLIAMS",
                    birthdate: "September 26, 1981",
                    age: "34",
                    country: "USA",
                    ranking: "1",
                    gender: "female",
                    tournament: "",
                    seed: "1",
                    draw_line_number: "1",
                    photo: "http://www.ausopen.com/images/players/wta230234.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Simona",
                    last_name: "HALEP",
                    birthdate: "September 27, 1991",
                    age: "24",
                    country: "ROU",
                    ranking: "2",
                    gender: "female",
                    tournament: "",
                    seed: "2",
                    draw_line_number: "128",
                    photo: "http://www.ausopen.com/images/players/wta314320.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Garbine",
                    last_name: "MUGURUZA",
                    birthdate: "October 8, 1993",
                    age: "22",
                    country: "ESP",
                    ranking: "3",
                    gender: "female",
                    tournament: "",
                    seed: "3",
                    draw_line_number: "96",
                    photo: "http://www.ausopen.com/images/players/wta316239.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Agnieszka",
                    last_name: "RADWANSKA",
                    birthdate: "March 6, 1989",
                    age: "26",
                    country: "POL",
                    ranking: "4",
                    gender: "female",
                    tournament: "",
                    seed: "4",
                    draw_line_number: "33",
                    photo: "http://www.ausopen.com/images/players/wta312251.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Maria",
                    last_name: "SHARAPOVA",
                    birthdate: "April 19, 1987",
                    age: "28",
                    country: "RUS",
                    ranking: "5",
                    gender: "female",
                    tournament: "",
                    seed: "5",
                    draw_line_number: "32",
                    photo: "http://www.ausopen.com/images/players/wta310137.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Petra",
                    last_name: "KVITOVA",
                    birthdate: "March 8, 1990",
                    age: "25",
                    country: "CZE",
                    ranking: "7",
                    gender: "female",
                    tournament: "",
                    seed: "6",
                    draw_line_number: "64",
                    photo: "http://www.ausopen.com/images/players/wta314206.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Angelique",
                    last_name: "KERBER",
                    birthdate: "January 18, 1988",
                    age: "28",
                    country: "GER",
                    ranking: "6",
                    gender: "female",
                    tournament: "",
                    seed: "7",
                    draw_line_number: "65",
                    photo: "http://www.ausopen.com/images/players/wta311470.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Venus",
                    last_name: "WILLIAMS",
                    birthdate: "June 17, 1980",
                    age: "35",
                    country: "USA",
                    ranking: "10",
                    gender: "female",
                    tournament: "",
                    seed: "8",
                    draw_line_number: "97",
                    photo: "http://www.ausopen.com/images/players/wta230220.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Karolina",
                    last_name: "PLISKOVA",
                    birthdate: "March 21, 1992",
                    age: "23",
                    country: "CZE",
                    ranking: "12",
                    gender: "female",
                    tournament: "",
                    seed: "9",
                    draw_line_number: "112",
                    photo: "http://www.ausopen.com/images/players/wta313974.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Carla",
                    last_name: "SUÃREZ NAVARRO",
                    birthdate: "September 3, 1988",
                    age: "27",
                    country: "ESP",
                    ranking: "11",
                    gender: "female",
                    tournament: "",
                    seed: "10",
                    draw_line_number: "49",
                    photo: "http://www.ausopen.com/images/players/wta311338.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Timea",
                    last_name: "BACSINSZKY",
                    birthdate: "June 8, 1989",
                    age: "26",
                    country: "SUI",
                    ranking: "14",
                    gender: "female",
                    tournament: "",
                    seed: "11",
                    draw_line_number: "80",
                    photo: "http://www.ausopen.com/images/players/wta311579.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Belinda",
                    last_name: "BENCIC",
                    birthdate: "March 10, 1997",
                    age: "18",
                    country: "SUI",
                    ranking: "13",
                    gender: "female",
                    tournament: "",
                    seed: "12",
                    draw_line_number: "17",
                    photo: "http://www.ausopen.com/images/players/wta319001.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Roberta",
                    last_name: "VINCI",
                    birthdate: "February 18, 1983",
                    age: "32",
                    country: "ITA",
                    ranking: "15",
                    gender: "female",
                    tournament: "",
                    seed: "13",
                    draw_line_number: "48",
                    photo: "http://www.ausopen.com/images/players/wta220214.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Victoria",
                    last_name: "AZARENKA",
                    birthdate: "July 31, 1989",
                    age: "26",
                    country: "BLR",
                    ranking: "16",
                    gender: "female",
                    tournament: "",
                    seed: "14",
                    draw_line_number: "81",
                    photo: "http://www.ausopen.com/images/players/wta312001.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Madison",
                    last_name: "KEYS",
                    birthdate: "February 17, 1995",
                    age: "20",
                    country: "USA",
                    ranking: "17",
                    gender: "female",
                    tournament: "",
                    seed: "15",
                    draw_line_number: "113",
                    photo: "http://www.ausopen.com/images/players/wta316959.jpg",
                    notes: ""
                  },
                  {
                    first_name: "Caroline",
                    last_name: "WOZNIACKI",
                    birthdate: "July 11, 1990",
                    age: "25",
                    country: "DEN",
                    ranking: "18",
                    gender: "female",
                    tournament: "",
                    seed: "16",
                    draw_line_number: "16",
                    photo: "http://www.ausopen.com/images/players/wta313402.jpg",
                    notes: ""
                  },


    ]
  return player_data
end



